### ISSUE TITLE
Sporadic conflict with tablet driver

### ISSUE THREAD

**Issue by tedmx** [segment-srl/htcap#3]
Hello there and thanks for your work! This error is exotic, sporadic and seems to go down to PhantomJS, but I think it will be useful to leave the report for it as I've found no similar reports for PhantomJS alone.

It's Windows 10.

On (usually second) `htcap.py crawl` command "There is a problem with your tablet driver" Windows error dialog pops up from PhantomJS process. 

I've done some simple debugging of htcap, and bug sits in there PhantomsJS works on commands recieved by `htcap.py crawl`. Also, any subsequent invocation of PhantomJS (including `phantomjs.exe --version`) brings the same tablet driver error. Until tablet drivers are killed, both `htcap crawl` and PhantomJS hang and don't work properly.

This tablet driver is something that rigs Wacom tablets. Probably PhantomJS tries to interact with that input while being used by htcap, and that brings on the error. I'll try to debug things by myself and get back with a more definite report.

**Comment by segment-srl** [comment]
Hi! yes very exotic.. unfortunately I cannot reproduce this issue since I've no wakom tablet.. have you tried to run htcap crawl -m passive ? In "passive mode" htcap will not trigger events and will not interact with inputs so no errors should occur. You can also try to set "mapEvents" and "triggerAllMappedEvents" to false in core/crawl/probe/options.js
thanks for the report!
