### ISSUE TITLE
After event(button click) triggered,page source updated,but program not analysis new page source

### ISSUE THREAD

**Issue by b1ueb0y** [segment-srl/htcap#6]
As issue title,we cannot get the link of click_link.php?id=2 in below website.
http://demo.aisec.cn/demo/aisec/

**Comment by segment-srl** [comment]
Hi,
Htcap analyzes the DOM modifications only if they come from an ajax request, so in your case the behaviour is correct.
Btw a bug exists because htcap fails to detect DOM changes if only one node is added. This bug is now fixed and I'm planning to add the ability to analyze any DOM change (regardless of ajax request) as an option.

**Comment by b1ueb0y** [comment]
@segment-srl  Look forward to new version which can analysis any  DOM change.
